export enum FunctionTags {
  "Ambassadeur" = "ambassadeur",
  "Ambassadeur pays" = "ambassadeur_pays",
  "Ambassadeur thématique" = "ambassadeur_thematique",
  "Avocat aux conseils" = "avocat_aux_conseils",
  "Cabinet" = "cabinet",
  "Cabinet ministériel" = "cabinet_ministeriel",
  "Centre de détention" = "centre_detention",
  "Commissaire de justice" = "commissaire_de_justice",
  "Commissaire de justice création d'office" = "commissaire_de_justice_creation_office",
  "Commissaire de justice résidence" = "commissaire_de_justice_residence",
  "Commissaire de justice résidence département code" = "commissaire_de_justice_residence_departement_code",
  "Commissaire gouvernement" = "commissaire_gouvernement",
  "Commission parlementaire" = "commission_parlementaire",
  "Conseil des ministres" = "conseil_des_ministres",
  "Conseiller des affaires étrangères" = "conseiller_affaire_etrangeres",
  "Consul" = "consul",
  "Cour administrative d'appel" = "cour_administrative_appel",
  "Cour d'appel" = "cour_appel",
  "Cour de cassation" = "cour_cassation",
  "Cour des comptes" = "cour_comptes",
  "Délégation parlementaire" = "delegation_parlementaire",
  "Directeur académie" = "directeur_academie",
  "Direction hôpital" = "direction_hopital",
  "Élève INSP/ENA" = "eleve_ena",
  "Élève ENS" = "eleve_ens",
  "Élève IRA" = "eleve_ira",
  "Élève Mines" = "eleve_mines",
  "Élève Polytechnique" = "eleve_polytechnique",
  "Élève Ponts et chaussées" = "eleve_ponts_et_chaussees",
  "Grade" = "grade",
  "Greffier" = "greffier",
  "Greffier résidence" = "greffier_residence",
  "Greffier résidence département code" = "greffier_residence_departement_code",
  "Haut fonctionnaire défense sécurité" = "haut_fonctionnaire_defense",
  "Huissier" = "huissier",
  "Huissier création office" = "huissier_creation_office",
  "Huissier résidence" = "huissier_residence",
  "Huissier résidence département code" = "huissier_residence_departement_code",
  "Légion d'honneur" = "legion_honneur",
  "Magistrat" = "magistrat",
  "Maitre de conférence" = "maitre_de_conference",
  "Médaille agrafe" = "medaille_agrafe",
  "Médaille militaire" = "medaille_militaire",
  "Médaille securité intérieure" = "medaille_securite_interieure",
  "Membre gouvernement" = "membre_gouvernement",
  "Ministre" = "ministre",
  "Notaire" = "notaire",
  "Notaire création d'office" = "notaire_creation_office",
  "Notaire résidence" = "notaire_residence",
  "Notaire résidence département code" = "notaire_residence_departement_code",
  "Notaire suppression d'office" = "notaire_suppression_office",
  "Notaire transfert d'office" = "notaire_tranfert_office",
  "Ordre du mérite" = "ordre_merite",
  "Ordre de la nation" = "ordre_nation",
  "Préfet" = "prefet",
  "Préfet de département" = "prefet_departement",
  "Préfet de département code" = "prefet_departement_code",
  "Préfet de région" = "prefet_region",
  "Président" = "president",
  "Professeur" = "professeur",
  "Professeur discipline" = "professeur_discipline",
  "Professeur section" = "professeur_section",
  "Recteur académie" = "recteur_academie",
  "Recteur région académique" = "recteur_region_academique",
  "Secrétaire des affaires étrangères" = "secretaire_affaires_etrangeres",
  "Secrétaire d'état" = "secretaire_etat",
  "Secrétaire général de préfecture" = "secretaire_general_de_prefecture",
  "Sous-préfecture de département code" = "sous-prefecture_departement_code",
  "Sous-préfet" = "sous-prefet",
  "Sous-préfet sous-préfecture" = "sous-prefet_sous-prefecture",
  "Tribunal" = "tribunal",
  "Tribunal administratif" = "tribunal_administratif",
  "Tribunal de commerce" = "tribunal_commerce",
  "Tribunal de grande instance" = "tribunal_grande_instance",
  "Tribunal d'instance" = "tribunal_instance",
  "Tribunal judiciaire" = "tribunal_judiciaire",
  "Tribunal pour enfants" = "tribunal_pour_enfants",
  "Tribunal de première instance" = "tribunal_premiere_instance",
  "Tribunal de proximité" = "tribunal_proximite",
  "Visa grands établissements" = "visa_grands_etablissements",
}

export function getFunctionsFromValues(
  values: FunctionTags[],
): (keyof typeof FunctionTags)[] {
  if (values.length === 0) return [];

  const tagValues = Object.values(FunctionTags);
  const tagKeys = Object.keys(FunctionTags) as (keyof typeof FunctionTags)[];

  return values.map((tag) => tagKeys[tagValues.indexOf(tag)]);
}
